### ISSUE TITLE
audio-only option please

### ISSUE THREAD

**Issue by wolftune** [antoniy/mozilla-youtube-dl-binding#43]
mpv has an easy option to disable video and just play audio, it would be great if that were a quick way to choose that from this plugin, alternatively, youtube-dl has -x which extracts just the audio, so either way…

(alternatively, maybe someone knows if video can be disabled after it's already playing in mpv, leaving just audio…)

**Comment by chew-z** [comment]
This project seems to be abandoned. 

My advice - create a separate profile in mpv config for firefox and set options according to your wishes.

In this plugin you can add commandline parameters so you can activate given profile. Create a few profiles if you have more usage scenarios.

In [mpv manual](https://mpv.io/manual/master/) there is a section regarding Profiles.

If you are using a Mac you can also create very simple Automator service calling mpv with options or profiles and use it instead of this plugin.

**Comment by gnikandrov** [comment]
Default keybinding in mpv for this is "_" (Shift+-).
The corresponding command in input.conf  (commented, because it's the default) is `#_ cycle video`.

**Comment by wolftune** [comment]
Thanks, but `_` doesn't work well with mpv-youtube plugin because it doesn't run in a terminal, so hitting _ just closes the window with audio still playing and thus no way to control or stop or anything.

It works well enough to just run in a terminal `mpv https://youtube-url` and then hit _ although it would be nice to have it work with this plugin

**Comment by gnikandrov** [comment]
I've added `--force-window=immediate` to the additional player parameters in about:addons and now it's just perfect for me. First of all, the mpv window pops up immediately after you select menu option from firefox (it's nice touch not having to guess whether mpv is just slow or youtube-dl somehow failed). And even if you press _, the video just stops, but the window is still there, so you can even turn video on again.

**Comment by wolftune** [comment]
@gnikandrov thanks, that works perfectly! Big improvement! I guess I'll consider this good enough and close this issue…
